TUP-502 : fixed NoCLassDefFoundError  The class net.sf.jasperreports.engine.export.JRPdfExporter in org.talend.libraries.jasperreport was expecting org.apache.commons.logging.classes but could not find any on the bundle classpath, so I added it to the required bundles.
git-svn-id: http://talendforge.org/svn/tos/trunk@99103 f6f1c999-d317-4740-80b0-e6d1abc6f99e